# 2D array
data in a two-dimensional grid are 2D array

In [4]:
import numpy as np

In [6]:
arra = np.array([[1,2,3], [4,5,6],[7,8,9]])

In [7]:
arra

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
type(arra)

numpy.ndarray

In [9]:
arra.ndim

2

In [10]:
arra.shape

(3, 3)

In [13]:
arra1 = np.array([[9,0],[2,4],[1,6]])

In [14]:
arra1

array([[9, 0],
       [2, 4],
       [1, 6]])

In [15]:
arra1.ndim

2

In [17]:
arra1.shape

(3, 2)

# Indexing and slicing

In [19]:
# indexing
arra = np.array([[1,2,3], [4,5,6],[7,8,9]])

In [20]:
arra

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arra[1,2]

6

In [24]:
arra[2,2]

9

In [26]:
arra[0,2]

3

In [27]:
arra[2,0]

7

In [29]:
# slicing
arra[:2, :2]

array([[1, 2],
       [4, 5]])

In [32]:
arra[0:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [34]:
arra[:, 1]

array([2, 5, 8])

In [35]:
arra[:, 2]

array([3, 6, 9])

In [37]:
arra

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arra[:,0]

array([1, 4, 7])

In [39]:
arra[1, :]

array([4, 5, 6])

# Matrix operation

# dot product , matrix multiplication - linear algebra

In [55]:
x = np.array([[2,3], [4,5], [6,7]])
y = np.array([[1,2,3], [10,23,8]])

In [56]:
x

array([[2, 3],
       [4, 5],
       [6, 7]])

In [57]:
x.shape

(3, 2)

In [58]:
y

array([[ 1,  2,  3],
       [10, 23,  8]])

In [59]:
y.shape

(2, 3)

In [67]:
output = np.dot(x,y)
output

array([[ 32,  73,  30],
       [ 54, 123,  52],
       [ 76, 173,  74]])

# Determinant

In [66]:
np.linalg.det(output)

0.0

In [68]:
x

array([[2, 3],
       [4, 5],
       [6, 7]])

In [69]:
y

array([[ 1,  2,  3],
       [10, 23,  8]])

In [73]:
np.linalg.det(np.array([[1,2],[6,7]]))

-5.000000000000001

In [74]:
np.floor(55.9)

55.0

In [75]:
np.ceil(55.9)

56.0

In [77]:
np.linalg.inv(np.array([[1,2],[6,7]]))

array([[-1.4,  0.4],
       [ 1.2, -0.2]])

# 2D axis : axis = 0 column-wise , axis = 1 row-wise

In [79]:
x = np.array([[2,3,4],[5,6,7]])
x

array([[2, 3, 4],
       [5, 6, 7]])

In [81]:
x.sum() # 2 + 3 + 4 + 5 + 6 + 7

27

In [83]:
x.sum(axis=0) # vertically ( 2 + 5), (3 + 6), (4 + 7)

array([ 7,  9, 11])

In [84]:
x.sum(axis=1) # horizontal (2 + 3 + 4), (5 + 6 + 7)

array([ 9, 18])

In [86]:
matrix = np.array([[2,3],[4,5],[6,7]])

In [87]:
matrix

array([[2, 3],
       [4, 5],
       [6, 7]])

In [88]:
matrix.sum()

27

In [89]:
matrix.sum(axis = 1)

array([ 5,  9, 13])

In [90]:
matrix.sum(axis = 0)

array([12, 15])

# .flatten()

In [92]:
matrix = np.array([[2,3],[4,5],[6,7]])

In [93]:
matrix

array([[2, 3],
       [4, 5],
       [6, 7]])

In [95]:
flatten_matrix = matrix.flatten()

In [96]:
flatten_matrix

array([2, 3, 4, 5, 6, 7])

# .reshape()

In [99]:
matrix = np.array([[2,3],[4,5],[6,7]])
matrix.shape

(3, 2)

In [100]:
x=matrix.reshape(2,3)

In [101]:
x

array([[2, 3, 4],
       [5, 6, 7]])

In [102]:
x.shape

(2, 3)

In [104]:
matrix.reshape(1,-1) # row matrix

array([[2, 3, 4, 5, 6, 7]])

In [106]:
matrix.reshape(-1, 1) # column matrix

array([[2],
       [3],
       [4],
       [5],
       [6],
       [7]])