# Numpy Methods

# zeros(), ones() and empty()





In [2]:
# zeros()
import numpy as np

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
x = np.zeros(12)

In [5]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
len(x)

12

In [9]:
x.shape

(12,)

In [11]:
# ones()
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
one = np.ones(100)

In [14]:
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
len(one)

100

In [17]:
one.shape

(100,)

In [19]:
# empty()
np.empty(6)

array([4.99176741e-310, 0.00000000e+000, 2.05833592e-312, 6.79038654e-313,
       2.14321575e-312, 2.27053550e-312])

In [20]:
m = np.empty(10)

In [21]:
m

array([4.99176732e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       1.21906088e-152, 1.48710905e-076, 3.27055474e+179, 6.86648467e-091,
       3.15839235e-033, 1.18600498e-259])

In [22]:
len(m)

10

In [23]:
m.shape

(10,)

# .arange()

In [24]:
np.arange(start=1, stop=10, step=2)

array([1, 3, 5, 7, 9])

In [25]:
m = np.arange(start=1, stop=10, step=2)

In [26]:
m

array([1, 3, 5, 7, 9])

In [27]:
len(m)

5

# .linspace()

In [30]:
np.linspace(start=1, stop=100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

# .sort() and .concatenate()

In [31]:
x = np.array([2,4,5,1,6,3])

In [33]:
np.sort(x)

array([1, 2, 3, 4, 5, 6])

In [34]:
np.flip(np.sort(x))

array([6, 5, 4, 3, 2, 1])

In [38]:
x = np.array([2, 3])
y = np.array([2, 4, 5])


In [36]:
x + y

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [40]:
np.concatenate([x,y])

array([2, 3, 2, 4, 5])

In [41]:
m = np.random.randint(low=1, high= 10, size=5)
n = np.random.randint(low=5, high= 15, size=6)


In [42]:
m

array([3, 2, 9, 4, 8])

In [43]:
n

array([ 5, 13,  5,  5, 14,  7])

In [44]:
m + n

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [45]:
np.concatenate([m, n])

array([ 3,  2,  9,  4,  8,  5, 13,  5,  5, 14,  7])