# Numpy
Numpy is python package, used for scientific computing

In [1]:
# to install numpy
! pip install numpy

In [2]:
# to import numpy
import numpy as np

In [3]:
# crating an empty array
z_array = np.array([])
type(z_array)

numpy.ndarray

In [4]:
z_array

array([], dtype=float64)

In [8]:
# creating empty array using empty list
list_x = []
array_x = np.array(list_x)

In [9]:
type(array_x)

numpy.ndarray

In [10]:
array_x

array([], dtype=float64)

In [11]:
# creating an array with divisible by 3 from 1 to 20
list_d_3 = [item for item in range(1,20) if item % 3 == 0]

In [12]:
array_d_3 = np.array(list_d_3)

In [13]:
array_d_3

array([ 3,  6,  9, 12, 15, 18])

In [15]:
type(array_d_3) # nd mean n-dimension

numpy.ndarray

In [17]:
# to check dimension of array
array_d_3.ndim # that means this is 1 dimension array


1

In [19]:
# shape
array_d_3.shape #(length-of-array)

(6,)

In [20]:
len(array_d_3)

6

In [22]:
# creating an array with odd number
array_odd = np.array([i for i in range(1,50) if i % 2 == 1])

In [23]:
array_odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [24]:
type(array_odd)

numpy.ndarray

In [25]:
len(array_odd)

25

In [26]:
array_odd.shape

(25,)

# List VS array

In [29]:
np.random.randint(1,5, size = 3) # creating random number between 1 to 5

array([2, 1, 2])

In [37]:
array_number = np.random.randint(low=1, high=50, size=50000)


In [38]:
array_number

array([32,  1, 12, ..., 13,  5, 25])

In [39]:
len(array_number)

50000

In [40]:
list_number = array_number.tolist()

In [ ]:
list_number

In [42]:
len(list_number)

50000

In [43]:
# checking computing time
%%time
cb = [item ** 3 for item in list_number ]

CPU times: user 13.5 ms, sys: 5.07 ms, total: 18.6 ms
Wall time: 18.4 ms


In [44]:
%%time
cb = array_number ** 3

CPU times: user 700 µs, sys: 0 ns, total: 700 µs
Wall time: 708 µs


# array operation are faster than list operation so, array is faster than list

In [45]:
list_data = [3.4, 5, True] # multiple data type

In [46]:
type(list_data)

list

In [50]:
array_data = np.array([list_data]) # homogeneous data type

In [49]:
array_data

array([[3.4, 5. , 1. ]])

In [51]:
l1 = [3, 4.5, False, 'Good Moring']

In [53]:
l1 # multiple data type


[3, 4.5, False, 'Good Moring']

In [64]:
array1 = np.array(l1)

In [65]:
array1 # all data is converted in str_

array(['3', '4.5', 'False', 'Good Moring'], dtype='<U32')

In [68]:
type(array1[0])

numpy.str_

# List supports multiple data type in contrast, array supports homogenous data type.

In [2]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [1]:
x_array = np.array([12,2,4,5,], dtype = np.int8)

NameError: name 'np' is not defined

In [ ]:
x_array