# Vector operation and Broadcasting

In [2]:
import numpy as np
x = np.array([2, 3])
y = np.array([5, 6])

In [3]:
x + y

array([7, 9])

In [4]:
x - y

array([-3, -3])

In [5]:
x * y

array([10, 18])

In [6]:
x / y

array([0.4, 0.5])

In [7]:
x ** y

array([ 32, 729])

In [8]:
x % y

array([2, 3])

In [9]:
x // y

array([0, 0])

# broadcasting

In [10]:
x = np.random.randint(low=1, high=50, size=5)

In [11]:
x

array([28,  3, 36, 33, 12])

In [12]:
3 + x

array([31,  6, 39, 36, 15])

In [13]:
4 - x

array([-24,   1, -32, -29,  -8])

In [14]:
5 * x

array([140,  15, 180, 165,  60])

In [15]:
2 / x

array([0.07142857, 0.66666667, 0.05555556, 0.06060606, 0.16666667])

In [16]:
5 % x

array([5, 2, 5, 5, 5])

In [17]:
3 ** x

array([    22876792454961,                 27, 150094635296999121,
         5559060566555523,             531441])

In [18]:
6 // x

array([0, 2, 0, 0, 0])

# .any() VS .all()

In [19]:
x = np.random.randint(low=1, high=50, size=10)

In [20]:
x

array([44, 30, 49, 16, 43, 17,  2, 15, 41, 19])

In [23]:
x >= 50

array([False, False, False, False, False, False, False, False, False,
       False])

In [22]:
np.any(x>50)

False

In [24]:
np.all(x>50)

False

In [26]:
np.any(x < 40)

True

In [27]:
np.all(x < 40)

False

In [28]:
x[x >= 40]

array([44, 49, 43, 41])

In [29]:
np.any(x[x >= 40])

True

In [31]:
np.all([x >= 40])

False

In [33]:
np.any((x==2) | (x==7))

True

In [34]:
np.any((x==3) | (x==7))


False

In [37]:
np.all(x[(x>10) & (x<20)])

True

In [39]:
x[(x>10) & (x<20)]


array([16, 17, 15, 19])

In [40]:
(x==3) | (x==7)

array([False, False, False, False, False, False, False, False, False,
       False])

In [41]:
(x>10) & (x<20)

array([False, False, False,  True, False,  True, False,  True, False,
        True])

In [42]:
np.all((x>10) & (x<20))

False

# Statistic using numpy

In [43]:
import numpy as np

In [44]:
x = np.random.randint(low=1, high=100, size=50)

In [45]:
x

array([30, 48, 37, 37, 10, 81, 43, 18, 65, 32,  3, 50, 42, 65, 18, 63, 97,
       58, 68, 73, 57, 11, 34, 26, 74,  4,  4, 56,  6, 48, 63, 47, 97, 81,
        8, 25, 66,  1, 31, 89, 40,  3, 84, 89, 42, 97, 20, 80, 33, 48])

In [47]:
# mean
x.mean()

46.04

In [48]:
np.mean(x)

46.04

In [50]:
# median
np.median(x)

45.0

In [52]:
# mode - to find mode of dataset need to import scipy library
from scipy.stats import mode
mode(x)

ModeResult(mode=48, count=3)

In [53]:
# standard  deviation
np.std(x)

28.20351751111907

In [54]:
# variance
np.var(x)

795.4384

In [55]:
# maximum
np.max(x)

97

In [56]:
# index of maximum data
np.argmax(x)

16

In [59]:
# minimum
np.min(x)

1

In [58]:
# index of minimum data
np.argmin(x)

37

In [60]:
num = np.random.randint(low=5, high=20, size=5)

In [61]:
num

array([ 7, 19, 14, 11, 16])

In [62]:
np.argmax(num)

1

In [63]:
np.argmin(num)

0